### ISSUE TITLE
Not implemented: window.computedStyle(elt, pseudoElt)

### ISSUE THREAD

**Issue by mehmetnyarar** [NickColley/jest-axe#147]
I am getting the following error for the following test with `jest-axe`:

Am I missing something?

> Error: Not implemented: window.computedStyle(elt, pseudoElt)

**test/setup.ts:**

```ts
import '@testing-library/jest-dom/extend-expect'
import 'jest-axe/extend-expect'
```

**file.spec.tsx:**

```tsx
const a11y = await axe(container)
expect(a11y).toHaveNoViolations()
```

**jest.config.js**

```js
{
  displayName: 'web:test',
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  testMatch: ['**/__tests__/**/+(*.)+(spec|test).+(js|ts)?(x)'],
  moduleNameMapper: {
    '^~/(.*)$': '<rootDir>/src/$1',
    '^test/(.*)$': '<rootDir>/test/$1'
  },
  setupFilesAfterEnv: ['<rootDir>/test/setup.ts'],
  globals: {
    'ts-jest': {
      tsconfig: {
        jsx: 'react'
      }
    }
  }
}
```

**deps:**

"jest": "^26.6.3",
"jest-axe": "^4.1.0",
"react-test-renderer": "^17.0.1",
"ts-jest": "^26.4.4",
"typescript": "^4.1.2"

**Comment by nickytonline** [comment]
I am experiencing this as well. For now, I've added the following to my tests where this fails. It's a noop patch for now.

Happy to dig into this @nickcolley if you're super busy.

describe('Some tests', () => {
  beforeAll(() => {
    // JSDom does not implement this and an error was being
    // thrown from jest-axe because of it.
    window.getComputedStyle = () => {};
  });

  // my tests ...
})

**Comment by GriffinSauce** [comment]
This workaround appears to break functionality in jest-axe, my simple check with a missing `<select>` label will return green when `window.getComputedStyle` is just replaced with a noop.  

As an alternative I've only stripped the second (unsupported) parameter and this at least keeps that test functional:

```.tsx
const { getComputedStyle } = window;
window.getComputedStyle = (elt) => getComputedStyle(elt);
```

You can add this in a [testSetup](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) file to apply to all tests instead of using a local `beforeAll`. That said: I expect that this will still introduce inaccuracy in tests, that second param must be there for a reason.

[This issue](https://github.com/jsdom/jsdom/issues/3025) in the jest-dom repo got a bit heated but the conclusion seems to be that it should not be fixed be fixed there... so does this belong with React Testing Library?

It appears to be fixed in [dom-testing-library](https://github.com/testing-library/dom-testing-library/issues/774) and subsequently [react-testing-library](https://github.com/testing-library/react-testing-library/pull/766) but I'm still getting it in newer versions of RTL.

So my conclusion is: I don't know where to go with this 😅

**Comment by zlargon** [comment]
@GriffinSauce's solution works for me.

I get the same error message after I upgrade the react-scripts from 3.x to 4.0.3 (without jest-axe)

**Comment by nickcolley** [comment]
Think this must be an issue upstream with axe-core itself since jest-axe just is a small wrapper, I'm also not sure where best to fix this.

Let me know if there's anything specific we can change in this package to resolve this issue if I'm incorrect.

Will close this for now but will be available for people to find when googling for the great workarounds posted to help others thank you.

**Comment by huangjihua** [comment]
```bash

      297 |      */
      298 |     function nodePseudoStyle(pseudoName) {
    > 299 |         const style = window.getComputedStyle(original, pseudoName);
          |                              ^
      300 |         const content = style.getPropertyValue('content');
      301 |         if (content === '' || content === 'none')
      302 |             return;

      at VirtualConsole.<anonymous> (node_modules/.pnpm/jest-environment-jsdom@29.0.3/node_modules/jest-environment-jsdom/build/index.js:70:23)
      at module.exports (node_modules/.pnpm/jsdom@20.0.0/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:12:26)
      at Window.getComputedStyle (node_modules/.pnpm/jsdom@20.0.0/node_modules/jsdom/lib/jsdom/browser/Window.js:798:7)
      at nodePseudoStyle (dist/es/dom-to-image.js:299:30)
      at dist/es/dom-to-image.js:292:76
          at Array.forEach (<anonymous>)
      at eachPseudoStyles (dist/es/dom-to-image.js:292:58)

  console.error
    Error: Not implemented: window.computedStyle(elt, pseudoElt)
        at module.exports (/Users/huangjihua/github/ts-dom-to-image/node_modules/.pnpm/jsdom@20.0.0/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at Window.getComputedStyle (/Users/huangjihua/github/ts-dom-to-image/node_modules/.pnpm/jsdom@20.0.0/node_modules/jsdom/lib/jsdom/browser/Window.js:798:7)
        at nodePseudoStyle (/Users/huangjihua/github/ts-dom-to-image/dist/es/dom-to-image.js:299:30)
        at /Users/huangjihua/github/ts-dom-to-image/dist/es/dom-to-image.js:292:76
        at Array.forEach (<anonymous>)
        at eachPseudoStyles (/Users/huangjihua/github/ts-dom-to-image/dist/es/dom-to-image.js:292:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      type: 'not implemented'

```

**Comment by NickColley** [comment]
Going to patch this in jest-axe itself, I think the main result is that any jest tests against pseudo elements may succeed, but that's better than people having to patch this manually themselves.

**Comment by NickColley** [comment]
Ok the 'proper' way to solve this is to turn off the color contrast checks in axe-core which'll never work in a JS Dom environment because visual checks cannot exist.

So I'm doing a patch but you can fix this yourself creating an instance with it turned off by default.

https://github.com/NickColley/jest-axe#setting-global-configuration

```javascripy// Global helper file (axe-helper.js)
const { configureAxe } = require("jest-axe");

const axe = configureAxe({
  checks: [
    {
      // color contrast checking doesnt work in a jsdom environment.
      id: "color-contrast",
      enabled: false,
    },
  ],
});

module.exports = axe
```

**Comment by sverona** [comment]
> Ok the 'proper' way to solve this is to turn off the color contrast checks in axe-core which'll never work in a JS Dom environment because visual checks cannot exist.
> 
> So I'm doing a patch but you can fix this yourself creating an instance with it turned off by default.
> 
> https://github.com/NickColley/jest-axe#setting-global-configuration
> 
> ```js
> // Global helper file (axe-helper.js)
> const { configureAxe } = require("jest-axe");
> 
> const axe = configureAxe({
>   checks: [
>     {
>       // color contrast checking doesnt work in a jsdom environment.
>       id: "color-contrast",
>       enabled: false,
>     },
>   ],
> });
> 
> module.exports = axe
> ```

The interface has changed since this post was made. Your setup file should contain something like:

```js
const axe = configureAxe({
  globalOptions: {
    checks: [
      {
        id: 'color-contrast',
        enabled: false,
      },
    ],
  },
});

export default axe;
```

**Comment by NickColley** [comment]
Colour contrast checks are turned off by default for any users with up to date version of the package, there's no need to do this manually I was sharing this for people who had not updated yet.
