### ISSUE TITLE
Certain ARIA roles must cotnain particular children

### ISSUE THREAD

**Issue by rusZoopla** [nickcolley/jest-axe#208]
We have recently encountered that jest-axe 5.0.1 does not detect this violation, but this same violation is detected by axe-DevTools browser extension. Need to update.

**Comment by afonsoduarte** [comment]
I was able to reproduce this bug: https://replit.com/@afonsoduarte/jest-axe-aria-required-children-bug?v=1#index.test.js

If you run that repl, you will notice the first test passes, since it does catch a role=listbox with a bad child. However, the second one, a role=listbox without any children, doesn't. 

The axe chrome extension catches both of these violations.

**Comment by afonsoduarte** [comment]
I've updated the Replit (https://replit.com/@afonsoduarte/jest-axe-aria-required-children-bug?v=1#index.test.js) to the jest-axe 6.0.0 but the issue persists. It seems like the issue is with axe-core though, so I'll open a bug there. I'll report back if it gets fixed upstream.
