### ISSUE TITLE
impactLevels does not exist in type 'JextAxeConfigureOptions'

### ISSUE THREAD

**Issue by chrisrhymes** [NickColley/jest-axe#231]
Thanks for this package, it looks great. 

I am trying to set up axe-jest using the [Setting the level of user impact](https://github.com/nickcolley/jest-axe#setting-the-level-of-user-impact) example in the readme, but typescript errors saying this is not an option? 

> Object literal may only specify known properties, and 'impactLevels' does not exist in type 'JestAxeConfigureOptions'

I am using jest v27, with @types/jest-axe v3.5, @testing-library/react v12 and React v17.0.2

**Comment by shunchu** [comment]
I did a little bit of digging and figured out that for `impactLevels` to work, it needs to be defined in the `axe-core` package's type definition for `RunOptions`.

Alternatively, we can amend it in the `index.d.ts` file of the `@types/jest-axe` package like so:

```typescript
export interface JestAxeConfigureOptions extends RunOptions {
    globalOptions?: Spec | undefined;
    impactLevels?: ImpactValue[]; // <-- added change
}
```

Maybe @NickColley can give me some guidance to see if that's an acceptable option. If so, I can submit a PR so that we can get this issue taken care of.

**Comment by NickColley** [comment]
I think the types are defined in a separate repository? So if you can find that I think they'd be okay with you contributing there. I'm not a big type script person so that's why it's not used directly in this project. I might consider doing those comments that turn into typescript compatible hints?

**Comment by shunchu** [comment]
@NickColley @chrisrhymes I opened a PR with the `@types/jest-axe` project: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62022

**Comment by shunchu** [comment]
@NickColley @chrisrhymes `impactLevels` support has finally been added to `@types/jest-axe`. That should resolve this issue. We are all good to go! 👍🏼

**Comment by NickColley** [comment]
Cheers!
