### ISSUE TITLE
Question: What is the difference between cypress-axe and jest-axe?

### ISSUE THREAD

**Issue by Vanals** [NickColley/jest-axe#281]
Hi!

About `cypress-axe` and `jest-axe`
In terms of efficiency, their ability to detect A11Y errors, what is the difference between the two?

What are the things that one is not able to do but the other one is, for instance?

I am using a Design system on a website. In the website I would like implement cypress-axe testing, but the design system tests their component with jest-axe.
Would there be differences in what the two type of tests can detect? What I want to avoid I having cypress axe test failing because jest-axe was used and so Jest not being able to detect what cypress-axe will fail for.

Thanks!

**Comment by NickColley** [comment]
Main thing you'll get from using cypress is the ability to automatically check colour contrast which is not possible with jest-axe since it does not use a real browser.
If you're already using something like cypress I recommend using something like cypress-axe over this package so you get that additional test coverage.
