### ISSUE TITLE
question on no-redundant-roles

### ISSUE THREAD

**Issue by VictorHom** [nickcolley/jest-axe#98]
https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-redundant-roles.md

my eslint set up points out that no-redundant-roles error, because it doesn't want me to do something like `<form role="form></form>`

jest-axe though will point out the following if I don't add role property:
```
    expect(received).toHaveNoViolations(expected)

    Expected the HTML found at $('form') to have no violations:

    <form>

    Received:

    "All page content must be contained by landmarks (region)"
```

is there a configuration for this? happy to help out if you need extra information or assistance.

**Comment by VictorHom** [comment]
I added a label to the form and that seems to fix the issue. I don't know the rules super well, so maybe that's to be expected, but the landmark error made me think that I needed role property.

**Comment by nickcolley** [comment]
Hey @VictorHom,

You're seeing this because axe prefers to be run on a full page.

So if your form element is not within a landmark, for example `<main>`, it'll warn you.

You could set a global configuration to opt out of this if you're testing components in isolation.

```js
const { configureAxe } = require('jest-axe')

const axe = configureAxe({
  rules: {
    // for demonstration only, don't disable rules that need fixing.
    'region': { enabled: false }
  }
})
```


https://github.com/nickcolley/jest-axe#setting-global-configuration

Will close this out but feel free to re-open if you need any more help.
